export default {
  plugins: ['prettier-plugin-tailwindcss'],
  printWidth: 96,
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  quoteProps: 'consistent',
  jsxSingleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  endOfLine: 'lf',
  proseWrap: 'preserve',
  embeddedLanguageFormatting: 'auto',
};
